#
# Makefile for the HENRY driver
#

obj-$(CONFIG_ALI_HENRY) += ali_device/

obj-$(CONFIG_HENRY_FIFO) += ali_device/

obj-$(CONFIG_HENRY_USUAL) += device/

obj-$(CONFIG_GLOBAL_MEM) += globalmem/

obj-$(CONFIG_GLOBAL_FIFO) += globalfifo/

obj-$(CONFIG_HENRY_GPIO) += gpio/

obj-$(CONFIG_SECOND_DEVICE) += second/

obj-$(CONFIG_VMEM_DISK) += vmem_disk/
