#
# Makefile for the globalfifo
#

obj-$(CONFIG_GLOBAL_FIFO) += globalfifo.o
globalfifo-$(CONFIG_GLOBAL_FIFO_NOBUS) := global_fifo.o
globalfifo-$(CONFIG_GLOBAL_FIFO_PLATFORM) := global_fifo_platform.o
globalfifo-$(CONFIG_GLOBAL_FIFO_MISC) := global_fifo_misc.o
