/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ledswitch_NativeLed */

#ifndef _Included_com_example_ledswitch_NativeLed
#define _Included_com_example_ledswitch_NativeLed
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ledswitch_NativeLed
 * Method:    openLedDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ledswitch_NativeLed_openLedDev
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ledswitch_NativeLed
 * Method:    operateLed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ledswitch_NativeLed_operateLed
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_example_ledswitch_NativeLed
 * Method:    closeLedDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ledswitch_NativeLed_closeLedDev
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
