/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dcmotor_NativeOperate */

#ifndef _Included_com_example_dcmotor_NativeOperate
#define _Included_com_example_dcmotor_NativeOperate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dcmotor_NativeOperate
 * Method:    openDCmotorDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_dcmotor_NativeOperate_openDCmotorDev
  (JNIEnv *, jobject);

/*
 * Class:     com_example_dcmotor_NativeOperate
 * Method:    operateDCmotor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_dcmotor_NativeOperate_operateDCmotor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_dcmotor_NativeOperate
 * Method:    closeDCmotorDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_dcmotor_NativeOperate_closeDCmotorDev
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
