/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_stepmotor_NativeOperate */

#ifndef _Included_com_example_stepmotor_NativeOperate
#define _Included_com_example_stepmotor_NativeOperate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_stepmotor_NativeOperate
 * Method:    openStepDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_stepmotor_NativeOperate_openStepDev
  (JNIEnv *, jobject);

/*
 * Class:     com_example_stepmotor_NativeOperate
 * Method:    operateStep
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_stepmotor_NativeOperate_operateStep
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_stepmotor_NativeOperate
 * Method:    closeStepDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_stepmotor_NativeOperate_closeStepDev
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
