/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_adcdisplay_NativeADC */

#ifndef _Included_com_example_adcdisplay_NativeADC
#define _Included_com_example_adcdisplay_NativeADC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_adcdisplay_NativeADC
 * Method:    openADCDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_adcdisplay_NativeADC_openADCDev
  (JNIEnv *, jobject);

/*
 * Class:     com_example_adcdisplay_NativeADC
 * Method:    startThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_adcdisplay_NativeADC_startThread
  (JNIEnv *, jobject);

/*
 * Class:     com_example_adcdisplay_NativeADC
 * Method:    closeADCDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_adcdisplay_NativeADC_closeADCDev
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
